<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;

class Post extends Model
{
    protected $table = 'posts';
    protected $fillable = ["forum_id", "user_id", "title", "slug", "description"];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($post){
            /**
             * Cuando la linea de comando no se este ejecutando
             * utilizaremos esto!!!
             */
            if(!App::runningInConsole()){
                $post->user_id = auth()->id();
            }
        });
    }

    public function forum(){
        return $this->belongsTo(Forum::class, 'forum_id');
    }

    public function owner(){
        return$this->belongsTo(User::class, 'user_id');
    }

    public function replies(){
        return $this->hasMany(Reply::class);
    }

    public function pathAttachment(){
        return "/images/posts/" . $this->attachment;
    }

}
