<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;

class Reply extends Model
{
    protected $table = 'replies';
    protected $fillable = ['user_id', 'post_id', 'reply'];

    protected $appends = ['forum'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($reply){
            /**
             * Cuando la linea de comando no se este ejecutando
             * utilizaremos esto!!!
             */
            if(!App::runningInConsole()){
                $reply->user_id = auth()->id();
            }
        });
    }

    public function post(){
        return $this->belongsTo(Post::class);
    }

    public function author(){
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getForumAttribute(){
        return $this->post->forum;
    }

    public function pathAttachment(){
        return "/images/replies/" . $this->attachment;
    }

}
